spring.application.name=energy-community

server.port=8083

# rabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# postresql
spring.datasource.url=jdbc:postgresql://localhost:5332/energydb
spring.datasource.username=lexan
spring.datasource.password=lexan

# Hibernate soll Tabellenstruktur automatisch aus den Entity-Klassen aktualisieren
spring.jpa.hibernate.ddl-auto=update

# Zeigt die von Hibernate ausgeführten SQL-Befehle im Terminal
spring.jpa.show-sql=true