services:
  db:
    container_name: postgres-energy-community
    image: postgres:latest
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: lexan
      POSTGRES_PASSWORD: lexan
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - energy-network
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq-energy-community
    image: rabbitmq:4-management
    ports:
      - "5672:5672"      # RabbitMQ für Spring Boot
      - "15672:15672"    # RabbitMQ Web UI
    networks:
      - energy-network
    restart: unless-stopped

networks:
  energy-network:
    driver: bridge

volumes:
  db: