spring.application.name=energy-api
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/energydb
spring.datasource.username=admin
spring.datasource.password=admin

# none bedeutet, dass Hibernate keine Tabellen anlegt oder ändert
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true