spring.application.name=community-producer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

rabbitmq.queue.name=energy-queue
rabbitmq.exchange.name=energy-exchange
rabbitmq.routing.key=energy.routing.key